name: Dev CI/CD

on:
  push:
    branches: [ "dev", "develop" ]
  pull_request:
    branches: [ "dev", "develop", "main", "staging" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Run Tests
      run: ./mvnw clean test



  open-pr-to-main:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR dev → staging.
        run: |
          # Check if PR already exists
          if gh pr list --base staging --head dev --state open --json number | jq -e 'length > 0' > /dev/null; then
            echo "PR already exists. Skipping..."
          else
            gh pr create \
              --base staging \
              --head dev \
              --title "chore: promote dev → staging" \
              --body "✅ All tests passed on dev. Auto-generated PR."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_PAT}}